export const FETCH_USERS_REQUEST = 'FETCH_USERS_REQUEST'; 
export const FETCH_USERS_SUCCESS = 'FETCH_USERS_SUCCESS'; 
export const FETCH_USERS_FAILURE = 'FETCH_USERS_FAILURE'; 

export const FETCH_PRODUCTS_PENDING = 'FETCH_PRODUCTS_PENDING';
export const FETCH_PRODUCTS_SUCCESS = 'FETCH_PRODUCTS_SUCCESS';
export const FETCH_PRODUCTS_ERROR = 'FETCH_PRODUCTS_ERROR';

export const INCREASE_PRODUCTS_COUNTER = 'INCREASE_PRODUCTS_COUNTER'; 
export const REDUCE_PRODUCTS_COUNTER = 'REDUCE_PRODUCTS_COUNTER'; 

